openapi: 3.0.1
info:
  title: Bolt.new Issue Reporting API
  version: '1.0.0'
  description: |
    Submit Bolt.new issues directly from the browser; issues are created
    in GitHub with context and stack traces.
servers:
  - url: http://localhost:3001/api
paths:
  /report:
    post:
      summary: Submit a new issue report
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IssueRequest'
      responses:
        '201':
          description: Issue created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  issueUrl:
                    type: string
        '400':
          description: Validation error
        '500':
          description: Server error
components:
  schemas:
    IssueRequest:
      type: object
      required:
        - title
      properties:
        title:
          type: string
        description:
          type: string
        context:
          type: object
          additionalProperties: true
